version: '3.8'

services:
  boilerplate:
    container_name: boilerplate-ts      # Change container name
    command: npm run watch
    restart: always
    build:
      context: .
      secrets:
        - npm
      target: development
    environment:
      HOST: $HOST
      PORT: $PORT
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3333/healthz" ]
      interval: 10m
      timeout: 10s
      retries: 3

    ports:
      - 3333:3333
    volumes:
      - ./:/usr/app

secrets:
  npm:
    file: ~/.npmrc